// site/src/examples/js/vue_component_display_code.vue
<script setup>
  import IntlTelInput from "intl-tel-input/vue";
  import "intl-tel-input/styles";

  const number = ref("");
  const isValid = ref(false);
  const errorCode = ref(0);
  const noticeMode = ref("off");

  const notice = computed(() => {
    // Determine the notice message based on the current state
  });

  const handleSubmit = () => {
    noticeMode.value = "submit";
  };

  const handleBlur = () => {
    noticeMode.value = "blur";
  };
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <IntlTelInput
      @changeNumber="number = $event"
      @changeValidity="isValid = $event"
      @changeErrorCode="errorCode = $event"
      :options="{
        initialCountry: 'us',
        loadUtils: () => import('intl-tel-input/utils'),
      }"
      :inputProps="{
        onBlur: handleBlur,
      }"
    />
    <button type="submit">Validate</button>
    <div v-if="notice" class="notice">{{ notice }}</div>
  </form>
</template>

// site/src/examples/js/react_component_display_code.js
import React, { useMemo, useState } from "react";
import IntlTelInput from "intl-tel-input/react";
import "intl-tel-input/styles";

const App = () => {
  const [number, setNumber] = useState("");
  const [isValid, setIsValid] = useState(false);
  const [errorCode, setErrorCode] = useState(0);
  const [noticeMode, setNoticeMode] = useState("off");

  const notice = useMemo(() => {
    // Determine the notice message based on the current state
  }, [noticeMode, isValid, number, errorCode]);

  const handleSubmit = (e) => {
    e.preventDefault();
    setNoticeMode("submit");
  };

  return (
    <form onSubmit={handleSubmit}>
      <IntlTelInput
        onChangeNumber={setNumber}
        onChangeValidity={setIsValid}
        onChangeErrorCode={setErrorCode}
        initOptions={{
          initialCountry: "us",
          loadUtils: () => import("intl-tel-input/utils"),
        }}
        inputProps={{
          name: "phone",
          onBlur: () => setNoticeMode("blur"),
        }}
      />
      <button type="submit">Validate</button>
      {notice && <div className="notice">{notice}</div>}
    </form>
  );
};
export default App;
